### ISSUE TITLE
Deal with new JSLint options

### ISSUE THREAD

**Issue by Sannis** [tav/nodelint#33]
There is some changes in JSLint defaults. I updated some of them as in @clebert fork (https://github.com/Sannis/nodelint/commit/7b033c5fce8b59b332bc350c23960c43b839d9c0).

But there is some options, that I've revert and what to discuss:
- `regexp:     false`, that disallow `.` in regexps
- `sloppy:     true`, that need `'use strict'` for all files
- `stupid:     true`, that disallow `...Sync` Node.js methods

There is no problem to fix this in nodelint sources, but what about users that will be affected by such update? I need some help to decide.

// cc: @tav, @mkitt, @cliffano, @paularmstrong, @codenothing, @mranney, @azatoth

**Comment by codenothing** [comment]
I'm thinking all need to be set to false and allow end user to change.

**Comment by paularmstrong** [comment]
`sloppy` is actually a tough one to support, since it (if I remember correctly) requires you to wrap every file in a method and place `use strict` at the top of that method.

Output from jslint.com is `Problem at line 1 character 1: Use the function form of 'use strict'.`

That will affect every file that everyone has written. And is really crappy in the node.js world, since the common pattern is to not wrap everything in a function form.

`regexp` seems fine to support, as it's one of those things that you should only turn off if you know what you're doing.

I can go either way on `stupid`.

**Comment by Sannis** [comment]
Thanks!

@paularmstrong, I've create an issue in JSLint repo to discuss this: https://github.com/douglascrockford/JSLint/issues/124
